### PR TITLE
Column Formatter 1.2

### PR DESCRIPTION
**Pull request by thechriskent**
| Q               | A
| --------------- | ---
| Bug fix?        | Yes
| New feature?    | Yes
| New sample?      | No
| Related issues?  | None

#### What's in this Pull Request?

Large update to 1.2 - See Change Log for full details.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx Chris for these. As this web part is evolving, it would be great to show that again for the community, so would you be interested on doing let's say 20 minutes on next Thursday in SPFx SIG call for this capability. You could do high-level intro on the column formatting in general, including the column formatting repository and then also demonstrate this web part and how it's implemented... a good combination of high-level intro on the capability, but also deep diving slightly on the actual SPFx implementation details.

If you have availability, that would be great. Timing would be 29th of March or if that's not suitable - then do this in the next general Dev sig on 5th of April. Thoughts?

cc @patrick-rodgers

**Comment by thechriskent** [comment]
Thanks Vesa! I would love to present on the call. Unfortunately, I'm traveling on the 29th, but 5th of April works great.

**Comment by VesaJuvonen** [comment]
Thx Chris, let's get you then scheduled for the 5th of April. That absolutely works as well and you can concentrate more on the showing the capability and also promoting the column formatting repo etc... where you have been also extremely active... we can give up to 30 min (your call) as based on the stats from our videos, we can see that when we cover things end-to-end, it does get more views - and that indicates that we simply should have more detailed end-to-end stories around different capabilities, like we recently did with hub sites. I'll get you anyway scheduled there and let me know how much time you'd like for this.

**Comment by VesaJuvonen** [comment]
Just to follow up on this and confirm this for Thursday - I'll do again 15-20 min on intro section around misc topic, then you - with 20-30 min - if you can do really end-to-end overview on the column formatting and showing GitHub samples etc. Value of column formatting and then obviously your custom solution for building them. This is not a SPFx call, so let's not deep dive on the actual web part code, rather keep it high level on that side.

**Comment by thechriskent** [comment]
Absolutely! 30 minutes should work great. The outline sounds perfect. The focus will be on understanding what column formatting is, how to use it, when to use it, and available resources (repo & webpart). I'll leave out details about how the webpart was built encouraging them to look at the code and ask questions offline if that's what they're interested in, but the focus is on the webpart as a tool (although I will totally promote the sp-dev-solutions repo as well). Looking forward to it!

**Pull request merged**
