### PR TITLE
[ModernSearch] Improved results placeholders

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes

#### What's in this Pull Request?

- Improved results placeholders. Now placeholders are defined by templates via a dedicated section.
- Miscelaneous fixes improving UI experience

### CODE REVIEW

**Comment by FranckyC** [comment]
That was quick

**Comment by FranckyC** [comment]
Did you test it before merging? ;)

**Comment by wobba** [comment]
I'm at the airport heading home from Vegas, of course I tested it 😁

**Comment by FranckyC** [comment]
All good then ;)

**Comment by wobba** [comment]
I'll test before merging to master for next release  👍

**Pull request merged**
