### PR TITLE
Search Pagination Web Part

### PR DESCRIPTION
**Pull request by YannickRe**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | 

#### What's in this Pull Request?
- Moved Pagination to separate web part

### CODE REVIEW

**Comment by wobba** [comment]
@YannickRe Cool idea. Question is, won't this add more white space above pagination due to web part space? cc @FranckyC

**Comment by YannickRe** [comment]
It is minimal, but I’ll get a before/after image tomorrow!
Reason for separation: I want pagination above and below results, bringing this even closer the Enterprise Search Center possibilities. Also allows easy overriding of just the paging web part.

**Comment by FranckyC** [comment]
Good addition @YannickRe. Haven't test yet but make sure the UI is not too impacted with white spaces.

**Comment by YannickRe** [comment]
@wobba @FranckyC Here is an side by side comparison. Left is as-is, right is with the pagination in a separate webpart (image was made before #69 ). I think the added white space is acceptable.
Integrated-Separate

**Comment by FranckyC** [comment]
@YannickRe Seems acceptable ;)

**Pull request closed without merging**
