### PR TITLE
Added WebhookHandlerFunction solution

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| New feature?    | yes

#### What's in this Pull Request?

This function allows to handle updates on a **list** by using a SharePoint webhook and a TypeScript Azure function.

### CODE REVIEW

**Comment by wobba** [comment]
Does this belong in solutions, or in one of the other repo's? What's it for? :)

**Comment by FranckyC** [comment]
It's not a Web Part and not an extension, I would imagine it belongs to the solutions repo since it is a _"...SharePoint development reusable solution..."_. @VesaJuvonen maybe you can tell where it should be?

**Comment by wobba** [comment]
@FranckyC solutions is more for end-user solutions. I absolutely see the value of this, just unsure where it would fit the best as it's a utility function/pattern. I'll wait for @VesaJuvonen to provide some input :)

**Comment by FranckyC** [comment]
@VesaJuvonen Any thoughts about this solution? Is this the right repo?

**Comment by VesaJuvonen** [comment]
The right location for this would be side-by-side with our other WebHook samples at https://github.com/SharePoint/sp-dev-samples/tree/master/Samples. It's been a while we have received a sample outside of the SPFx topics, but this is a repository where we will be also gradually moving relevant samples from other older PnP repositories....

**Comment by VesaJuvonen** [comment]
Let's relocate the sample and I'll close this one. Sorry for not being clear on the locations, but hopefully this clarifies the situation. Whenever we get the upcoming sample portal up and running, all samples will be nicely exposed using polished UIs so there's no concerns of samples getting lost... still work in progress, but in pipeline.

**Comment by wobba** [comment]
Thank you for clarifying this @VesaJuvonen :)

**Comment by FranckyC** [comment]
Thanks @VesaJuvonen. I didn't know about this repo (too many PnP repos byt he time!). It's a shame because it would deserve a better exposure I think. Since there is already a sample using Azure Function/Node.js, should I submit this sample anyway?

**Pull request closed without merging**
