### PR TITLE
[ModernSearch] Upgrade projects to SPFx v1.8.2

### LINKED ISSUE #99: [ModernSearch] Upgrade to SPFx v1.8.2
I'm planning to start the upgrade of the Modern Search to v1.8.1 of SPFx. Current plan are the following steps, if there are concerns/other approaches etc. let me know before I start ;)
@FranckyC @wobba 

#### Todo
- [x] Upgrade to SPFX v1.8.2
- [x] Upgrade to TypeScript v3.3
- [ ] ~Upgrade Office UI Fabric React~

### PR DESCRIPTION
**Pull request by YannickRe**
| Q               | A
| --------------- | ---
| Related issues?  | fixes #99 

#### What's in this Pull Request?
Upgrade both the main project and the renderers project to v1.8.2 of SPFx.
- I took a dependency on `office-ui-fabric` to keep the ootb templates working. We might want work on removing this dependency.
- I added `"loadLegacyFabricCss": true,` to `SearchResultsWebPart.manifest.json` to keep the ootb templates working. We might want to find a way to remove this again.

@wobba Can you test with custom styling? I saw you kept reverting to `"@microsoft/sp-office-ui-fabric-core": "1.6.0",` and I'm not sure why or how to test. I now updated this to `1.8.2` 😃

@FranckyC & @taraldga: fyi, if you see an issue with the upgrade, just let me know

### CODE REVIEW

**Comment by wobba** [comment]
The 1.6.0 dep was because newer versions failed on parsing correct theme colors. Should be easy to test by using `ms-fontColor-themePrimary` and similar in a template and see if it turns out blue or the correct theme color.

**Comment by YannickRe** [comment]
Does that work in the hosted workbench? Or only on an actual page?

**Comment by wobba** [comment]
Don't remember 🙂 load via ?manifest param on a page to be 100% I guess (not at a pc now)

**Comment by FranckyC** [comment]
Nice work! I can't test right now but just make sure you can still use office ui fabric styles in handlebars template with the current accordance (button for instance). Thank again.

**Comment by YannickRe** [comment]
@wobba This still fails with 1.8.2, did you log a bug for it? Although I'm afraid they won't fix it, since office-ui-fabric is deprecated... What do you suggest now? Put it back at 1.6.0?

@FranckyC I didn't touch any imports and made sure that office-ui-fabric is now a dependency, I'm guesssing this still works as expected.
StylingWith182

As said, I do think we need to find a way to make this work without having a dependency on `office-ui-fabric`. It blocks our upgrade to later versions of the `@microsoft/sp-office-ui-fabric-core` package and it is/has been deprecated a long time.

**Comment by wobba** [comment]
Can you target the dev branch? and I'll merge before testing.

**Comment by YannickRe** [comment]
Sorry, didn't pay attention but it's changed now!

**Comment by wobba** [comment]
We could use 1.6.0 or make our own fix - which is better I believe.

**Pull request merged**
