### PR TITLE
Feature/search refiners

### PR DESCRIPTION
**Pull request by YannickRe**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes
| New sample?      | no
| Related issues?  | discussed in #64

#### What's in this Pull Request?
- Upgraded Modern Search web part to SPFx 1.7.1
- Fixed Search Navigation Web Part
  - Made manifest file consistent with the other web parts
  - Dynamic Data workaround consistent with other web parts
  - Used React container pattern
- Fixed Search Box Web Part
  - Used React container pattern
- Created Search Refiners Web Part
  - Gets search results from Search Results web part
  - Is responsible for refiners configuration, exposes it as a datasource
  - Exposes selected refiner filters as a datasource
- Search Results Web Part
  - Renamed, because everything related to refiners is now in a separate web part
  - Reads selected refiners and refiners config from Refiners web part

### CODE REVIEW

**Comment by wobba** [comment]
I'll review this later. Thank you 👍

**Comment by FranckyC** [comment]
I've just tested out and It is ok for me. @wobba you can merge it I think. I'm currently working on your code @YannickRe to use single dynamic data object instead of mapping each property on by one. An other PR will follow based on this one. Great job!

**Comment by wobba** [comment]
There's a merge conflict.

**Comment by FranckyC** [comment]
Due to the upgrade to 1.7.1 I guess

**Comment by YannickRe** [comment]
Something I'm supposed to do now?

**Comment by wobba** [comment]
@YannickRe can you pull the latest and merge into your commit to resolve the issues? (on my phone right now). git fetch upstream, should work if you are tracking the main repo.

**Comment by YannickRe** [comment]
Working on it

**Comment by wobba** [comment]
...and sorry for causing this ☺️

**Comment by YannickRe** [comment]
Done!

**Pull request merged**
