### PR TITLE
[ModernSearch] Refiners WP bug fixes

### LINKED ISSUE #106: [Modern Search] Date filter
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Very nice additon with this date filter, clearly something our users were really asking for, thank you !!
But i found a few bugs around this functionnality : 
- i have several other refiners and when other refiners got recalculate to reflect the results filtered by date, my date choice is not displayed anymore
- when i filter by date, my property "technical" name is shown below the filter button and not the actual date or at least the displayValue of the refiner...
image

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| Related issues?  | fixes #106 

#### What's in this Pull Request?

* Fixed bugs regarding Office UI Fabric GroupedList component https://github.com/SharePoint/sp-dev-solutions/issues/106

### CODE REVIEW

**Comment by FranckyC** [comment]
@wobba Don't know why it conflicts but you can take my version for these files

**Comment by wobba** [comment]
@FranckyC can you fix the merge conflicts?

**Comment by FranckyC** [comment]
@wobba should be ok now

**Comment by wobba** [comment]
Merged into master as well

**Pull request merged**
