### PR TITLE
[ModernSearch] Fixes for #184 and #198

### LINKED ISSUE #184: Can i use theme color in custom html (handler)
@FranckyC  if yes, how can i do that

### LINKED ISSUE #198: Search Box WebPart with "Send Query to a new page" behave different on clicking "X" (Clear).
#### Category

- [ ] Bug

#### Expected or Desired Behavior
Configuring Search Box web part with "Send Query to a new page". When entering some values in search box and click on Clear button, instead of clearing the text, it redirects to other page.

#### Observed Behavior
Configuring Search Box web part with "Send Query to a new page". When entering some values in search box and click on Clear button, instead of clearing the text, it redirects to other page.

#### Steps to Reproduce
1) Configuring Search Box web part with "Send Query to a new page".
2) Enter search text the "X" button will appear to clear the text.
3) When you click on "X", instead of clearing the text it redirects to other page.

Thanks for your contribution! Sharing is caring.

### PR DESCRIPTION
**Pull request by YannickRe**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| Related issues?  | fixes #184 & #198 

#### What's in this Pull Request?
**Fix #198**: when using Search Box and send to another page, when clearing the entry with the clear button, it would still redirect to the "another page". This is now fixed, it just clears the textbox and doesn't redirect anymore.

**Fix #184**: hacky workaround to once again allow the use of `ms-fontColor-themePrimary` and the likes in custom templates.
In SearchResultsTemplate.scss we include the CSS from `office-ui-fabric` (which is deprecated), and this file includes definitions for `ms-fontColor-themePrimary` etc with default colors. We then include the CSS from `sp-office-ui-fabric-core`. Up to SPFx 1.6.0, this CSS would also include those definitions but with SharePoint themed colors and effectively overriding the previously loaded values.
After 1.6.0 SPFx didn't provide these overrides anymore, since they are considered deprecated.

The workaround is to include the overrides from 1.6.0 in our web parts directly. This restores functionality but is not a sustainable solution.
If and when a big refactoring comes up, we need to make sure we address this differently, and make sure we stop depending on `office-ui-fabric`

@wobba @FranckyC

### CODE REVIEW

**Comment by FranckyC** [comment]
Thanks @YannickRe  for the PR! FYI I'm currently working on something to remove the office ui fabric js library. Looking forward to finish this to show you the results ;)

**Comment by wobba** [comment]
@YannickRe would it be possible to use `color: "[theme: themePrimary, default: #0078d7]"` notation instead in the mixins to clean up any ui-fabric css reference?

**Comment by YannickRe** [comment]
@wobba I think that’s possible, but the mixins are also included in the SP-Office-fabric package included with SPFx.
Let me know, I’ll do it next week when I return from France 😉

**Comment by wobba** [comment]
@YannickRe if we can remove deps to both `sp-office-ui-fabric-core` and `office-ui-fabric` to make it smaller, or end up with just `sp-office-ui-fabric-core` we'd be better off :) Today the full css i 25kb of the gzip'd bundle, so quite large.

image

**Comment by YannickRe** [comment]
Yup, I’ll spend some time next week to reduce this.

**Pull request merged**
