### PR TITLE
Allow users to define the placeholder text in the search-box webpart. 

### PR DESCRIPTION
**Pull request by taraldga**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | no

#### What's in this Pull Request?

Added the possisbility to define the placeholdertext in the webpart settings of the search box. The old placeholder texts are kept as default values if no text is provided in the settings.

### CODE REVIEW

**Comment by harshdamaniahd** [comment]
Is this working ?

**Comment by wobba** [comment]
@harshdamaniahd build and test :)

**Comment by harshdamaniahd** [comment]
no its not working

**Comment by wobba** [comment]
@taraldga any idea?

**Comment by harshdamaniahd** [comment]
Hey @wobba , I can see the placeholder now, dont know how.It is working. Let you know if any issues.Thanks.

**Pull request merged**
