### PR TITLE
[ModernSearch] Added refiners templates + default multi value/date pickers filters

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| New feature?    | yes
| Related issues?  |  #72 (see roadmap)

#### What's in this Pull Request?
Added new capability for the refiners WP. Now we are able to select builtin templates for each refiner:

- Single value (default mode)
- Multi value 
- Date pickers (from, to)

The behavior is the same as the classic SharePoint search experience. Migration should be seamless for previous refiners configuration.

### CODE REVIEW

**Comment by FranckyC** [comment]
WTF @wobba you never sleep ;)

**Comment by wobba** [comment]
I get up at 06:28 😁

**Comment by FranckyC** [comment]
@wobba @YannickRe @taraldga If you have time to test it quickly just to be sure it does not break anything.

**Comment by YannickRe** [comment]
I’ll test somewhere this weekend! Sounds like a nice addition!

**Comment by FranckyC** [comment]
It is!  but it is also a big refactoring on how refinements work so I would to be sure everything works as excepted.

**Comment by YannickRe** [comment]
@FranckyC First, very quick review:

- Local workbench, putting all the webparts on the page (except navigation) and connecting them. With the default settings, I get a cannot access property of undefined message, when you try to map the configuredValue with the returned refiners (which in the MockService don't match the configured refiners).
- The date range from-to is awesome but changing the "from" already triggers a search request, which "scrolls" the page. Maybe better to wait for a "to" to be filled in, or also include an "apply" button like with the multivalue.
- The date range also forces at least a range of 1 month, is that a limitation of the api or (un)expected behaviour? Might be interesting to document (when you update the readme).

Looks awesome and is awesome feature set, I'll test it with our current project on Sunday (probably).

**Comment by YannickRe** [comment]
Also got this warning when building
`[20:46:08] Warning - tslint - src\webparts\searchRefiners\SearchRefinersWebPart.ts(319,59): error semicolon: Missing semicolon`

**Comment by FranckyC** [comment]
Thanks @YannickRe I'll check

**Comment by YannickRe** [comment]
@FranckyC My analysis of the data range picker wasn't correct.

If I select a data in the past in "From", the earliest date I can select in "To" is selected day + 1 in the current month. Examples executed today, March 31, 2019 would give:
  - From: February 11, 2019 => To: March 12, 2019
  - From: January 1, 2019 => To: March 2, 2019

**Comment by FranckyC** [comment]
@YannickRe Thank you for the tests, You've right about data ranges. Should be fixed now. I will leave the search triggers as is for now since it is a valid scenario (we don't need a 'to' or 'from' value for a data search).

**Pull request merged**
