### PR TITLE
Added {QueryString.<ParameterName>} token parsing

### LINKED ISSUE #76: How to use Query String Parameters with Search Result WebPart
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I would like to use a URL querystring parameter in the search result web part but not sure how to do it.

In the first screen It is configured to use the page environment, querystring and my URL parameter is selected.

In my page URL I have ?ListItemId=1. So how do I use this querystring parameter?
I'v been trying in my search request: ListItemId={QueryString.ListItemId} but it does not work.
I know that ListeItemId=1 is working.

Thanks!

### PR DESCRIPTION
**Pull request by YannickRe**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | fixes #76 

#### What's in this Pull Request?
* Extracted token replacement/variable parsing into a separate service
* Moved responsibility of token parsing into the SearchService instead of the SearchResultsWebPart. This makes sure that everyone using the SearchService will get the token parsing as well.
* Added support for {QueryString.<ParameterName>} token
* Increased version number and adjusted readme

@wobba @FranckyC Mind validating?

### CODE REVIEW

**Comment by YannickRe** [comment]
@FranckyC True, but the SearchService also receives the whole webpart context already. I can change for the TokenService, you want me to apply the change for SearchService as well?

**Comment by FranckyC** [comment]
@YannickRe Yep, in this case, the SearchService should also use necessary properties as well. That was a bad habit never refactored :(.

**Comment by YannickRe** [comment]
@FranckyC I made the change, difficult to decide the granularity... Mind checking again?

**Comment by wobba** [comment]
There are also merge conflicts here now :)

**Comment by YannickRe** [comment]
Haha, I’ll take care of those later!

**Comment by YannickRe** [comment]
Merge conflicts resolved!

**Pull request merged**
