### PR TITLE
[ModernSearch] Refiner WP bug fixes

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| Bug fix?        | yes

#### What's in this Pull Request?
- Fixed an issue about min and max calculation for date pickers as pointed out by @YannickRe in #101 
- Added translations for multilingual scenarios for date pickers
- Fixed local workbench scenario

### CODE REVIEW

**Comment by wobba** [comment]
I haven't had time to test a lot lately, so let me know when you think everything is stable and I'll merge to master.

**Comment by FranckyC** [comment]
@wobba I compared with classic search experience with same multi value refiners configuration and the results are the same as the modern WP. Should be good merge in master.

**Comment by YannickRe** [comment]
I’ll find some time today to do a quick check, great job!

**Comment by wobba** [comment]
@YannickRe let me know when you have done final testing and I'll merge it.

**Comment by YannickRe** [comment]
@wobba In a live environment, I don't see any issues anymore so I think this can be merged.
@FranckyC In the local workbench, the refiners now load and filter but every filter that gets applied ends up with 0 results. Don't know if we need to spent more time on this, but might be worth mentioning as known issue/behavior or something?

**Comment by FranckyC** [comment]
@YannickRe thank you for the tests. The local workbench data are not so relevant so it does not matter I think.

**Pull request merged**
